services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: agendify_user
      POSTGRES_PASSWORD: askjdbuias100ahnsd1asdas
      POSTGRES_DB: agendify_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: